---

- name: Create a ORACLE_HOME directory
  become_user: root
  tags: app
  file:
    dest: "{{oracle_home}}"
    mode: 0755
    owner: "{{oracle_user}}"
    group: "{{oracle_install_group}}"
    state: directory

- name : Copy the JDK and Weblogic Installation files to ORACLE_HOME
  become_user: root
  tags: app,cpbinaries
  copy: 
    src: "{{ item }}" 
    dest: "{{ oracle_home }}"
    mode: 0755
    owner: "{{oracle_user}}"
    group: "{{oracle_install_group}}"
  with_items:
    - "fmw_12.2.1.4.0_wls.jar"
    - "jdk-8u221-linux-x64.tar.gz"
    - "oraInst.loc"
    - "install.file"
    - "DemoIdentity.jks"

- name: Copy the Template files 
  tags: cpscripts
  template:
     src: "{{ item.src }}"
     dest: "{{ oracle_home }}/{{item.dest}}"
     mode: 0755
  with_items:
    - { src: 'CreateDomain.sh.j2', dest: 'CreateDomain.sh' }
    - { src: 'create-wls-domain.py.j2', dest: 'create-wls-domain.py' }
    - { src: 'Map-Resources.j2', dest: 'Map-Resources.py' }

- name : Install java
  tags: installjava, app
  shell: "/usr/bin/gzip -dc jdk-8u221-linux-x64.tar.gz | /usr/bin/tar xf -"
  args:
   chdir: "{{ oracle_home }}"
  environment:
   JAVA_HOME: "{{ oracle_home }}/jdk1.8.0_221"
   PATH: "$PATH:{{ oracle_home }}/jdk1.8.0_221/bin"

- name: Crate a Soft link to java
  become_user: root
  tags: linkjava
  file:
    src: "{{oracle_home}}/jdk1.8.0_221/bin/java"
    dest: "/usr/bin/java"
    state: link
  ignore_errors: true

- name : Validate Java
  tags: app,vjava
  command: "java -version"
  register: javaver

- debug:
    msg: " Java Version Found {{ javaver.stderr }}"

- name: Install Weblogic 
  tags: installweblogic,app
  register: wlsinstall
  shell: "java -jar {{ oracle_home}}/fmw*.jar -silent -invPtrLoc {{oracle_home}}/oraInst.loc -responseFile {{oracle_home}}/install.file -ignoreSysPrereqs -force -novalidation ORACLE_HOME={{oracle_home}} INSTALL_TYPE='WebLogic Server'"
  args:
    chdir: "{{ oracle_home }}"
  when: "'java version \"1.8.0_221\"' in javaver.stderr"
  failed_when: "'failed' in wlsinstall.stderr"
  changed_when: "'already installed' not in wlsinstall.stdout"


- name: Set WLST Environment and Create Domain
  tags: app,createdomain
  shell:  "./CreateDomain.sh"
  register: setwlsenv
  args:
    chdir: "{{ oracle_home }}"
  when: "{{ ansible_hostname == groups['app'][0] }}"
  environment:
          USER_MEM_ARGS: "-Djava.security.egd=file:/dev/./urandom" 

- debug:
    msg: "{{ setwlsenv.stdout_lines }}"
  when: "{{ ansible_hostname == groups['app'][0] }}"
  

- name: validating if the AdminServer is already started and running
  tags: amprevalidate
  wait_for:
    host: "{{groups['app'][0]}}"
    port: "{{admin_ListenPort}}"
    delay: 10
    timeout: 30
    state: started
  when: ansible_hostname == "{{groups['app'][0]}}"
  register: amprevalidate
  ignore_errors: true

- name: Start the AdminServer
  tags: startadminserver
  shell: "./startWebLogic.sh > adminserver.log &"
  args:
    chdir: "{{oracle_home}}/domains/{{domain_name}}/bin/"
  register: startadminserver
  run_once: yes
  when: ansible_hostname == "{{ groups['app'][0] }}" and amprevalidate is failed
  environment:
          USER_MEM_ARGS: "-Djava.security.egd=file:/dev/./urandom"

- name: wait for the adminserver to start and open the port 
  tags: amvalidate
  wait_for:
    host: "{{groups['app'][0]}}"
    port: "{{admin_ListenPort}}"
    delay: 10
    timeout: 120
    state: started
  when: ansible_hostname == "{{groups['app'][0]}}"

- name: Map Resources - Cluster and Machine
  tags: mapresources
  shell:  "source {{oracle_home}}/domains/{{domain_name}}/bin/setDomainEnv.sh && java weblogic.WLST {{ oracle_home }}/Map-Resources.py"
  register: mapresources
  args:
    chdir: "{{ oracle_home }}"
  when: "{{ ansible_hostname == groups['app'][0] }}"
  environment:
          USER_MEM_ARGS: "-Djava.security.egd=file:/dev/./urandom" 


- name: pack command execution
  shell: "{{ wlshome }}/common/bin/pack.sh -domain={{domainroot}}/{{domain_name}} -template=/tmp/mwi.jar -template_name=remote_managed -managed=true"
  register: packcommand
  run_once: true
  tags: app,packit
  failed_when: "packcommand.stderr"
  when: "{{ ansible_hostname == groups['app'][0] }}"

- name: display pack template
  tags: packit
  run_once: true
  command: "ls -lrt /tmp/mwi.jar"
  register: output
  failed_when: " 'No' in output.stderr"
  when: "{{ ansible_hostname == groups['app'][0] }}"

- name: change permission
  tags: packit
  run_once: true
  file:
    path: "{{item}}"
    mode: 0775
  with_items:
    - "/tmp/mwi.jar"
  when: "{{ ansible_hostname == groups['app'][0] }}"

- name: Copy the file
  tags: sync,packit
  synchronize:
    src: "{{ item }}"
    dest: "{{ item }}"
    mode: push
  delegate_to: "{{groups['app'][0]}}"
  register: syncfile
  with_items:
   - "/tmp/mwi.jar"
  when: ansible_hostname == "{{groups['app'][1]}}"

- name: Run the unpack operation
  shell: "{{ wlshome }}/common/bin/unpack.sh -domain={{domainroot}}/{{domain_name}} -template=/tmp/mwi.jar"
  register: unpack
  tags: app,unpack,packit
  when: ansible_hostname == "{{groups['app'][1]}}"

- name: set the SSL listener to false in nodemanager.properties file
  tags: replaceline
  lineinfile:
    dest: "{{ domainroot}}/{{ domain_name }}/nodemanager/nodemanager.properties"
    regexp: '{{item.from}}'
    line: '{{item.to}}'
    state: present
    backup: yes
  register: replaceline
  with_items:
     - { from: "^SecureListener=true" , to: "SecureListener=false" }
     - { from: "^ListenAddress=localhost" , to: "ListenAddress=" }

- name: start the nodemanager
  tags: startnodemanager
  shell: "./startNodeManager.sh > nodemanager.log &"
  args:
    chdir: "{{domainroot}}/{{domain_name}}/bin/"
  register: startNodemanager

- name: wait for the nodemanager to start and open the port
  tags: nmvalidate
  wait_for:
    host: "localhost"
    port: 5556
    delay: 10
    timeout: 120
    state: started
